project_id = "lihctrhzsyjqnlzwwkzo"

[functions.send-push-notification]
verify_jwt = false

[functions.send-match-activity-digest]
verify_jwt = false

[functions.notify-new-message-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
