/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActorsRouteImport } from './routes/actors'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AdminCategoriesRouteImport } from './routes/admin-categories'
import { Route as AdminFunctionLogsRouteImport } from './routes/admin-function-logs'
import { Route as AdminReportsRouteImport } from './routes/admin-reports'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as AdminSupportRouteImport } from './routes/admin-support'
import { Route as ApiAccessRouteImport } from './routes/api-access'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CreativeDirectorsRouteImport } from './routes/creative-directors'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as DancersRouteImport } from './routes/dancers'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as DesignersRouteImport } from './routes/designers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ForcePasswordChangeRouteImport } from './routes/force-password-change'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GraphicDesignersRouteImport } from './routes/graphic-designers'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MasterAdminRouteImport } from './routes/master-admin'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MusicProducersRouteImport } from './routes/music-producers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OpenProjectsRouteImport } from './routes/open-projects'
import { Route as PhotographersRouteImport } from './routes/photographers'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupProfileRouteImport } from './routes/setup-profile'
import { Route as SoftwareDevelopersRouteImport } from './routes/software-developers'
import { Route as SongwritersRouteImport } from './routes/songwriters'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SynkAiRouteImport } from './routes/synk-ai'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VideographersRouteImport } from './routes/videographers'
import { Route as WhoLikedYouRouteImport } from './routes/who-liked-you'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogHowToFindAMusicProducerRouteImport } from './routes/blog/how-to-find-a-music-producer'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ExploreNearbyRouteImport } from './routes/explore/nearby'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsCitySlugRouteImport } from './routes/locations/$citySlug'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as StudioItemIdRouteImport } from './routes/studio/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsRoute = ActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin-categories',
  path: '/admin-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFunctionLogsRoute = AdminFunctionLogsRouteImport.update({
  id: '/admin-function-logs',
  path: '/admin-function-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin-reports',
  path: '/admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin-support',
  path: '/admin-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRoute = ApiAccessRouteImport.update({
  id: '/api-access',
  path: '/api-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeDirectorsRoute = CreativeDirectorsRouteImport.update({
  id: '/creative-directors',
  path: '/creative-directors',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const DancersRoute = DancersRouteImport.update({
  id: '/dancers',
  path: '/dancers',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersRoute = DesignersRouteImport.update({
  id: '/designers',
  path: '/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcePasswordChangeRoute = ForcePasswordChangeRouteImport.update({
  id: '/force-password-change',
  path: '/force-password-change',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicDesignersRoute = GraphicDesignersRouteImport.update({
  id: '/graphic-designers',
  path: '/graphic-designers',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAdminRoute = MasterAdminRouteImport.update({
  id: '/master-admin',
  path: '/master-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicProducersRoute = MusicProducersRouteImport.update({
  id: '/music-producers',
  path: '/music-producers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenProjectsRoute = OpenProjectsRouteImport.update({
  id: '/open-projects',
  path: '/open-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersRoute = PhotographersRouteImport.update({
  id: '/photographers',
  path: '/photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/setup-profile',
  path: '/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareDevelopersRoute = SoftwareDevelopersRouteImport.update({
  id: '/software-developers',
  path: '/software-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const SongwritersRoute = SongwritersRouteImport.update({
  id: '/songwriters',
  path: '/songwriters',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SynkAiRoute = SynkAiRouteImport.update({
  id: '/synk-ai',
  path: '/synk-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VideographersRoute = VideographersRouteImport.update({
  id: '/videographers',
  path: '/videographers',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoLikedYouRoute = WhoLikedYouRouteImport.update({
  id: '/who-liked-you',
  path: '/who-liked-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToFindAMusicProducerRoute =
  BlogHowToFindAMusicProducerRouteImport.update({
    id: '/blog/how-to-find-a-music-producer',
    path: '/blog/how-to-find-a-music-producer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreNearbyRoute = ExploreNearbyRouteImport.update({
  id: '/explore/nearby',
  path: '/explore/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCitySlugRoute = LocationsCitySlugRouteImport.update({
  id: '/locations/$citySlug',
  path: '/locations/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioItemIdRoute = StudioItemIdRouteImport.update({
  id: '/studio/$itemId',
  path: '/studio/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/actors': typeof ActorsRoute
  '/admin': typeof AdminRoute
  '/admin-auth': typeof AdminAuthRoute
  '/admin-categories': typeof AdminCategoriesRoute
  '/admin-function-logs': typeof AdminFunctionLogsRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-support': typeof AdminSupportRoute
  '/api-access': typeof ApiAccessRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/creative-directors': typeof CreativeDirectorsRoute
  '/credits': typeof CreditsRoute
  '/dancers': typeof DancersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/designers': typeof DesignersRoute
  '/discover': typeof DiscoverRoute
  '/edit-profile': typeof EditProfileRoute
  '/features': typeof FeaturesRoute
  '/feed': typeof FeedRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/gallery': typeof GalleryRoute
  '/graphic-designers': typeof GraphicDesignersRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/licenses': typeof LicensesRoute
  '/marketplace': typeof MarketplaceRoute
  '/master-admin': typeof MasterAdminRoute
  '/matches': typeof MatchesRoute
  '/music-producers': typeof MusicProducersRoute
  '/notifications': typeof NotificationsRoute
  '/open-projects': typeof OpenProjectsRoute
  '/photographers': typeof PhotographersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-profile': typeof SetupProfileRoute
  '/software-developers': typeof SoftwareDevelopersRoute
  '/songwriters': typeof SongwritersRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/super-admin': typeof SuperAdminRoute
  '/synk-ai': typeof SynkAiRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/videographers': typeof VideographersRoute
  '/who-liked-you': typeof WhoLikedYouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/how-to-find-a-music-producer': typeof BlogHowToFindAMusicProducerRoute
  '/explore/nearby': typeof ExploreNearbyRoute
  '/locations/$citySlug': typeof LocationsCitySlugRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/studio/$itemId': typeof StudioItemIdRoute
  '/auth/': typeof AuthIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/actors': typeof ActorsRoute
  '/admin': typeof AdminRoute
  '/admin-auth': typeof AdminAuthRoute
  '/admin-categories': typeof AdminCategoriesRoute
  '/admin-function-logs': typeof AdminFunctionLogsRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-support': typeof AdminSupportRoute
  '/api-access': typeof ApiAccessRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/creative-directors': typeof CreativeDirectorsRoute
  '/credits': typeof CreditsRoute
  '/dancers': typeof DancersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/designers': typeof DesignersRoute
  '/discover': typeof DiscoverRoute
  '/edit-profile': typeof EditProfileRoute
  '/features': typeof FeaturesRoute
  '/feed': typeof FeedRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/gallery': typeof GalleryRoute
  '/graphic-designers': typeof GraphicDesignersRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/licenses': typeof LicensesRoute
  '/marketplace': typeof MarketplaceRoute
  '/master-admin': typeof MasterAdminRoute
  '/matches': typeof MatchesRoute
  '/music-producers': typeof MusicProducersRoute
  '/notifications': typeof NotificationsRoute
  '/open-projects': typeof OpenProjectsRoute
  '/photographers': typeof PhotographersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-profile': typeof SetupProfileRoute
  '/software-developers': typeof SoftwareDevelopersRoute
  '/songwriters': typeof SongwritersRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/super-admin': typeof SuperAdminRoute
  '/synk-ai': typeof SynkAiRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/videographers': typeof VideographersRoute
  '/who-liked-you': typeof WhoLikedYouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/how-to-find-a-music-producer': typeof BlogHowToFindAMusicProducerRoute
  '/explore/nearby': typeof ExploreNearbyRoute
  '/locations/$citySlug': typeof LocationsCitySlugRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/studio/$itemId': typeof StudioItemIdRoute
  '/auth': typeof AuthIndexRoute
  '/blog': typeof BlogIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/actors': typeof ActorsRoute
  '/admin': typeof AdminRoute
  '/admin-auth': typeof AdminAuthRoute
  '/admin-categories': typeof AdminCategoriesRoute
  '/admin-function-logs': typeof AdminFunctionLogsRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-support': typeof AdminSupportRoute
  '/api-access': typeof ApiAccessRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/creative-directors': typeof CreativeDirectorsRoute
  '/credits': typeof CreditsRoute
  '/dancers': typeof DancersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/designers': typeof DesignersRoute
  '/discover': typeof DiscoverRoute
  '/edit-profile': typeof EditProfileRoute
  '/features': typeof FeaturesRoute
  '/feed': typeof FeedRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/gallery': typeof GalleryRoute
  '/graphic-designers': typeof GraphicDesignersRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/licenses': typeof LicensesRoute
  '/marketplace': typeof MarketplaceRoute
  '/master-admin': typeof MasterAdminRoute
  '/matches': typeof MatchesRoute
  '/music-producers': typeof MusicProducersRoute
  '/notifications': typeof NotificationsRoute
  '/open-projects': typeof OpenProjectsRoute
  '/photographers': typeof PhotographersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-profile': typeof SetupProfileRoute
  '/software-developers': typeof SoftwareDevelopersRoute
  '/songwriters': typeof SongwritersRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/super-admin': typeof SuperAdminRoute
  '/synk-ai': typeof SynkAiRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/videographers': typeof VideographersRoute
  '/who-liked-you': typeof WhoLikedYouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/how-to-find-a-music-producer': typeof BlogHowToFindAMusicProducerRoute
  '/explore/nearby': typeof ExploreNearbyRoute
  '/locations/$citySlug': typeof LocationsCitySlugRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/studio/$itemId': typeof StudioItemIdRoute
  '/auth/': typeof AuthIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/actors'
    | '/admin'
    | '/admin-auth'
    | '/admin-categories'
    | '/admin-function-logs'
    | '/admin-reports'
    | '/admin-settings'
    | '/admin-support'
    | '/api-access'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/creative-directors'
    | '/credits'
    | '/dancers'
    | '/data-deletion'
    | '/designers'
    | '/discover'
    | '/edit-profile'
    | '/features'
    | '/feed'
    | '/force-password-change'
    | '/gallery'
    | '/graphic-designers'
    | '/home'
    | '/how-it-works'
    | '/jobs'
    | '/licenses'
    | '/marketplace'
    | '/master-admin'
    | '/matches'
    | '/music-producers'
    | '/notifications'
    | '/open-projects'
    | '/photographers'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/setup-profile'
    | '/software-developers'
    | '/songwriters'
    | '/success-stories'
    | '/super-admin'
    | '/synk-ai'
    | '/teams'
    | '/terms'
    | '/videographers'
    | '/who-liked-you'
    | '/auth/callback'
    | '/blog/how-to-find-a-music-producer'
    | '/explore/nearby'
    | '/locations/$citySlug'
    | '/messages/$conversationId'
    | '/profile/$userId'
    | '/projects/$projectId'
    | '/settings/notifications'
    | '/studio/$itemId'
    | '/auth/'
    | '/blog/'
    | '/explore/'
    | '/locations/'
    | '/messages/'
    | '/profile/'
    | '/projects/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/actors'
    | '/admin'
    | '/admin-auth'
    | '/admin-categories'
    | '/admin-function-logs'
    | '/admin-reports'
    | '/admin-settings'
    | '/admin-support'
    | '/api-access'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/creative-directors'
    | '/credits'
    | '/dancers'
    | '/data-deletion'
    | '/designers'
    | '/discover'
    | '/edit-profile'
    | '/features'
    | '/feed'
    | '/force-password-change'
    | '/gallery'
    | '/graphic-designers'
    | '/home'
    | '/how-it-works'
    | '/jobs'
    | '/licenses'
    | '/marketplace'
    | '/master-admin'
    | '/matches'
    | '/music-producers'
    | '/notifications'
    | '/open-projects'
    | '/photographers'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/setup-profile'
    | '/software-developers'
    | '/songwriters'
    | '/success-stories'
    | '/super-admin'
    | '/synk-ai'
    | '/teams'
    | '/terms'
    | '/videographers'
    | '/who-liked-you'
    | '/auth/callback'
    | '/blog/how-to-find-a-music-producer'
    | '/explore/nearby'
    | '/locations/$citySlug'
    | '/messages/$conversationId'
    | '/profile/$userId'
    | '/projects/$projectId'
    | '/settings/notifications'
    | '/studio/$itemId'
    | '/auth'
    | '/blog'
    | '/explore'
    | '/locations'
    | '/messages'
    | '/profile'
    | '/projects'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/actors'
    | '/admin'
    | '/admin-auth'
    | '/admin-categories'
    | '/admin-function-logs'
    | '/admin-reports'
    | '/admin-settings'
    | '/admin-support'
    | '/api-access'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/creative-directors'
    | '/credits'
    | '/dancers'
    | '/data-deletion'
    | '/designers'
    | '/discover'
    | '/edit-profile'
    | '/features'
    | '/feed'
    | '/force-password-change'
    | '/gallery'
    | '/graphic-designers'
    | '/home'
    | '/how-it-works'
    | '/jobs'
    | '/licenses'
    | '/marketplace'
    | '/master-admin'
    | '/matches'
    | '/music-producers'
    | '/notifications'
    | '/open-projects'
    | '/photographers'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/setup-profile'
    | '/software-developers'
    | '/songwriters'
    | '/success-stories'
    | '/super-admin'
    | '/synk-ai'
    | '/teams'
    | '/terms'
    | '/videographers'
    | '/who-liked-you'
    | '/auth/callback'
    | '/blog/how-to-find-a-music-producer'
    | '/explore/nearby'
    | '/locations/$citySlug'
    | '/messages/$conversationId'
    | '/profile/$userId'
    | '/projects/$projectId'
    | '/settings/notifications'
    | '/studio/$itemId'
    | '/auth/'
    | '/blog/'
    | '/explore/'
    | '/locations/'
    | '/messages/'
    | '/profile/'
    | '/projects/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActorsRoute: typeof ActorsRoute
  AdminRoute: typeof AdminRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFunctionLogsRoute: typeof AdminFunctionLogsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  ApiAccessRoute: typeof ApiAccessRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CreativeDirectorsRoute: typeof CreativeDirectorsRoute
  CreditsRoute: typeof CreditsRoute
  DancersRoute: typeof DancersRoute
  DataDeletionRoute: typeof DataDeletionRoute
  DesignersRoute: typeof DesignersRoute
  DiscoverRoute: typeof DiscoverRoute
  EditProfileRoute: typeof EditProfileRoute
  FeaturesRoute: typeof FeaturesRoute
  FeedRoute: typeof FeedRoute
  ForcePasswordChangeRoute: typeof ForcePasswordChangeRoute
  GalleryRoute: typeof GalleryRoute
  GraphicDesignersRoute: typeof GraphicDesignersRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JobsRoute: typeof JobsRoute
  LicensesRoute: typeof LicensesRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MasterAdminRoute: typeof MasterAdminRoute
  MatchesRoute: typeof MatchesRoute
  MusicProducersRoute: typeof MusicProducersRoute
  NotificationsRoute: typeof NotificationsRoute
  OpenProjectsRoute: typeof OpenProjectsRoute
  PhotographersRoute: typeof PhotographersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupProfileRoute: typeof SetupProfileRoute
  SoftwareDevelopersRoute: typeof SoftwareDevelopersRoute
  SongwritersRoute: typeof SongwritersRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  SuperAdminRoute: typeof SuperAdminRoute
  SynkAiRoute: typeof SynkAiRoute
  TeamsRoute: typeof TeamsRoute
  TermsRoute: typeof TermsRoute
  VideographersRoute: typeof VideographersRoute
  WhoLikedYouRoute: typeof WhoLikedYouRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogHowToFindAMusicProducerRoute: typeof BlogHowToFindAMusicProducerRoute
  ExploreNearbyRoute: typeof ExploreNearbyRoute
  LocationsCitySlugRoute: typeof LocationsCitySlugRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  StudioItemIdRoute: typeof StudioItemIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors': {
      id: '/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-categories': {
      id: '/admin-categories'
      path: '/admin-categories'
      fullPath: '/admin-categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-function-logs': {
      id: '/admin-function-logs'
      path: '/admin-function-logs'
      fullPath: '/admin-function-logs'
      preLoaderRoute: typeof AdminFunctionLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports': {
      id: '/admin-reports'
      path: '/admin-reports'
      fullPath: '/admin-reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-support': {
      id: '/admin-support'
      path: '/admin-support'
      fullPath: '/admin-support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-access': {
      id: '/api-access'
      path: '/api-access'
      fullPath: '/api-access'
      preLoaderRoute: typeof ApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-directors': {
      id: '/creative-directors'
      path: '/creative-directors'
      fullPath: '/creative-directors'
      preLoaderRoute: typeof CreativeDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dancers': {
      id: '/dancers'
      path: '/dancers'
      fullPath: '/dancers'
      preLoaderRoute: typeof DancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers': {
      id: '/designers'
      path: '/designers'
      fullPath: '/designers'
      preLoaderRoute: typeof DesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-password-change': {
      id: '/force-password-change'
      path: '/force-password-change'
      fullPath: '/force-password-change'
      preLoaderRoute: typeof ForcePasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-designers': {
      id: '/graphic-designers'
      path: '/graphic-designers'
      fullPath: '/graphic-designers'
      preLoaderRoute: typeof GraphicDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-admin': {
      id: '/master-admin'
      path: '/master-admin'
      fullPath: '/master-admin'
      preLoaderRoute: typeof MasterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-producers': {
      id: '/music-producers'
      path: '/music-producers'
      fullPath: '/music-producers'
      preLoaderRoute: typeof MusicProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-projects': {
      id: '/open-projects'
      path: '/open-projects'
      fullPath: '/open-projects'
      preLoaderRoute: typeof OpenProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers': {
      id: '/photographers'
      path: '/photographers'
      fullPath: '/photographers'
      preLoaderRoute: typeof PhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-profile': {
      id: '/setup-profile'
      path: '/setup-profile'
      fullPath: '/setup-profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-developers': {
      id: '/software-developers'
      path: '/software-developers'
      fullPath: '/software-developers'
      preLoaderRoute: typeof SoftwareDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songwriters': {
      id: '/songwriters'
      path: '/songwriters'
      fullPath: '/songwriters'
      preLoaderRoute: typeof SongwritersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synk-ai': {
      id: '/synk-ai'
      path: '/synk-ai'
      fullPath: '/synk-ai'
      preLoaderRoute: typeof SynkAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videographers': {
      id: '/videographers'
      path: '/videographers'
      fullPath: '/videographers'
      preLoaderRoute: typeof VideographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-liked-you': {
      id: '/who-liked-you'
      path: '/who-liked-you'
      fullPath: '/who-liked-you'
      preLoaderRoute: typeof WhoLikedYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-find-a-music-producer': {
      id: '/blog/how-to-find-a-music-producer'
      path: '/blog/how-to-find-a-music-producer'
      fullPath: '/blog/how-to-find-a-music-producer'
      preLoaderRoute: typeof BlogHowToFindAMusicProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/nearby': {
      id: '/explore/nearby'
      path: '/explore/nearby'
      fullPath: '/explore/nearby'
      preLoaderRoute: typeof ExploreNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$citySlug': {
      id: '/locations/$citySlug'
      path: '/locations/$citySlug'
      fullPath: '/locations/$citySlug'
      preLoaderRoute: typeof LocationsCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$itemId': {
      id: '/studio/$itemId'
      path: '/studio/$itemId'
      fullPath: '/studio/$itemId'
      preLoaderRoute: typeof StudioItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActorsRoute: ActorsRoute,
  AdminRoute: AdminRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFunctionLogsRoute: AdminFunctionLogsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  ApiAccessRoute: ApiAccessRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CreativeDirectorsRoute: CreativeDirectorsRoute,
  CreditsRoute: CreditsRoute,
  DancersRoute: DancersRoute,
  DataDeletionRoute: DataDeletionRoute,
  DesignersRoute: DesignersRoute,
  DiscoverRoute: DiscoverRoute,
  EditProfileRoute: EditProfileRoute,
  FeaturesRoute: FeaturesRoute,
  FeedRoute: FeedRoute,
  ForcePasswordChangeRoute: ForcePasswordChangeRoute,
  GalleryRoute: GalleryRoute,
  GraphicDesignersRoute: GraphicDesignersRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  JobsRoute: JobsRoute,
  LicensesRoute: LicensesRoute,
  MarketplaceRoute: MarketplaceRoute,
  MasterAdminRoute: MasterAdminRoute,
  MatchesRoute: MatchesRoute,
  MusicProducersRoute: MusicProducersRoute,
  NotificationsRoute: NotificationsRoute,
  OpenProjectsRoute: OpenProjectsRoute,
  PhotographersRoute: PhotographersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupProfileRoute: SetupProfileRoute,
  SoftwareDevelopersRoute: SoftwareDevelopersRoute,
  SongwritersRoute: SongwritersRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  SuperAdminRoute: SuperAdminRoute,
  SynkAiRoute: SynkAiRoute,
  TeamsRoute: TeamsRoute,
  TermsRoute: TermsRoute,
  VideographersRoute: VideographersRoute,
  WhoLikedYouRoute: WhoLikedYouRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogHowToFindAMusicProducerRoute: BlogHowToFindAMusicProducerRoute,
  ExploreNearbyRoute: ExploreNearbyRoute,
  LocationsCitySlugRoute: LocationsCitySlugRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  StudioItemIdRoute: StudioItemIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
